name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main  # à chaque push sur la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Cloner ton dépôt
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Se connecter à Azure Container Registry
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CONTAINER_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_PASSWORD }}

    # 3️⃣ Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/ml-api:latest .

    # 4️⃣ Pousser l'image vers Azure Container Registry
    - name: Push image to Azure Container Registry
      run: |
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/ml-api:latest

    # 5️⃣ Déployer sur ton App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: fastapi-ml-app  # ⚠️ remplace par le nom exact de ton App Service
        images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/ml-api:latest
